services:

  glance-hub:
    image: ${GLANCE_IMAGE:-glanceapp/glance}:${GLANCE_VERSION:-latest}
    container_name: glance-hub
    restart: always
    networks:
      default:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/api/healthz" ]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - 8081:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./hub/pages:/app/config/pages:ro
      - ./hub/glance.yml:/app/config/glance.yml:ro
      - ./shared/assets:/app/assets:ro
      - ./shared/widgets:/app/config/widgets:ro
      - ./shared/variables.yml:/app/config/variables.yml:ro
      - ./shared/theme.yml:/app/config/theme.yml:ro

  glance-dev:
    image: ${GLANCE_IMAGE:-glanceapp/glance}:${GLANCE_VERSION:-latest}
    container_name: glance-dev
    restart: always
    networks:
      default:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/api/healthz" ]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - 8082:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dev/pages:/app/config/pages:ro
      - ./dev/glance.yml:/app/config/glance.yml:ro
      - ./shared/assets:/app/assets:ro
      - ./shared/widgets:/app/config/widgets:ro
      - ./shared/variables.yml:/app/config/variables.yml:ro
      - ./shared/theme.yml:/app/config/theme.yml:ro

networks:
  default:
