services:

  glance-hub:
    image: ${GLANCE_IMAGE:-glanceapp/glance}:${GLANCE_VERSION:-latest}
    container_name: glance-hub
    restart: always
    networks:
      default:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/api/healthz" ]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./hub/pages:/app/config/pages
      - ./hub/glance.yml:/app/config/glance.yml
      - ./shared/assets:/app/assets
      - ./shared/widgets:/app/config/widgets
      - ./shared/variables.yml:/app/config/variables.yml
    labels:
      glance.group: Apps
      glance.id: glance-hub
      glance.name: Glance Hub
      glance.description: Homepage
      glance.icon: si:gitee
      glance.url: ${GLANCE_HUB_URL}

  glance-dev:
    image: ${GLANCE_IMAGE:-glanceapp/glance}:${GLANCE_VERSION:-latest}
    container_name: glance-dev
    restart: always
    networks:
      default:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/api/healthz" ]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 10s
    env_file:
      - .env
    ports:
      - 8082:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dev/pages:/app/config/pages
      - ./dev/glance.yml:/app/config/glance.yml
      - ./shared/assets:/app/assets
      - ./shared/widgets:/app/config/widgets
      - ./shared/variables.yml:/app/config/variables.yml
    labels:
      glance.group: Apps
      glance.id: glance-dev
      glance.name: Glance Dev
      glance.description: Dashboard
      glance.icon: si:gitee
      glance.url: ${GLANCE_DEV_URL}

networks:
  default:
