- &backube-base
  type: custom-api
  title: Youtube Videos
  cache: *no-cache
  frameless: true
  url: ${BACKUBE_URL}/api/feed
  css-class: x-backube
  options:
    collapse-after-rows: 4
  parameters:
    perPage: 32
    skipTotal: 1
  template: |
    {{ $items := .JSON.Array `#.{"id":id,"title":title,"url":{"fn":!"replace","val":id,"href":!"https://www.youtube.com/watch?v={val}"},"header":[{"tpl":!"Title"}],"image":{"fn":!"replace","val":id,"src":!"https://i.ytimg.com/vi/{val}/hqdefault.jpg","overlays":[{"class":!"x-center x-play","tpl":!"PlayIcon"}]},"footer":[{"class":!"","tpl":!"WeirdTime","val":published},{"class":!"","tpl":!"Link","val":{"title":channel_title,"link":{"fn":!"replace","val":channel,"href":!"https://www.youtube.com/channel/{val}/videos" }}}]}`
    }}
    $include: /components/templates.gohtml
    $include: /components/media.gohtml
    $include: /components/media-container.gohtml
